services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prn232-lms-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - prn232_lms_sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prn232-lms-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PRN232_LMS;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False"
      Database__EnsureCreatedOnStartup: "true"
    ports:
      - "8080:8080"

volumes:
  prn232_lms_sql_data:
